name: Veracode Static Code Analysis

run-name: Static Code Analysis - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: 
       - scala-pipeline-scan
       - scala-policy-scan
       - scala-sandbox-scan
       - java-maven-pipeline-scan
       - java-maven-policy-scan
       - java-maven-sandbox-scan
       - java-gradle-pipeline-scan
       - java-gradle-policy-scan
       - java-gradle-sandbox-scan
       - ruby-pipeline-scan
       - ruby-policy-scan
       - ruby-sandbox-scan
       - dot-net-pipeline-scan
       - dot-net-policy-scan
       - dot-net-sandbox-scan
       - php-pipeline-scan
       - php-policy-scan
       - php-sandbox-scan
       - tsql-pipeline-scan
       - tsql-policy-scan
       - tsql-sandbox-scan
       - plsql-pipeline-scan
       - plsql-policy-scan
       - plsql-sansbox-scan
       - source-code-pipeline-scan
       - source-code-policy-scan
       - source-code-sandbox-scan

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: veracode/Veracode-github-app@aws-ecs-dynamodb
      with:
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        branch: ${{ github.event.client_payload.branch }}
        run_id: ${{ github.run_id }}
        repository_owner: ${{ github.event.client_payload.repository.owner }}
        repository_name: ${{ github.event.client_payload.repository.name }}
        event_type: ${{ github.event.client_payload.event_type }}
        enforce: true
        
  build:
    needs: register
    uses: ./.github/workflows/veracode-build-artifact-for-scanning.yml
    with:
      repository: ${{ github.event.client_payload.repository.full_name }}
      ref: ${{ github.event.client_payload.sha }}
      token: ${{ github.event.client_payload.token }}
      event_name: ${{ github.event.action }}


  pipeline_scan:
    # needs the build step before this job will start running
    needs: build
    if: contains(github.event.action, 'pipeline')
    uses: ./.github/workflows/veracode-pipeline-scan.yml
    secrets: inherit
    
  policy_scan:
    needs: build
    if: contains(github.event.action, 'policy')
    uses: ./.github/workflows/veracode-policy-scan.yml
    with:
      profile_name: ${{ github.event.client_payload.profile_name }}
      moddules_to_scan: ${{ github.event.client_payload.modules_to_scan }}
    secrets: inherit

  sanbox_scan:
    needs: build
    if: contains(github.event.action, 'sandbox')
    uses: ./.github/workflows/veracode-sandbox-scan.yml
    with:
      profile_name: ${{ github.event.client_payload.profile_name }}
      moddules_to_scan: ${{ github.event.client_payload.modules_to_scan }}
      branch: ${{ github.event.client_payload.branch }}
    secrets: inherit
